Repository Kernel360/E2E1-KernelEngine, pull requests merged in 2023-11, with the labels that each got.

#42 [Feature] 서비스 메인 페이지에 feed 리스트 붙임
  build.gradle
  src/main/java/com/example/e2ekernelengine/crawler/service/ChannelRssCrawler.java
  src/main/java/com/example/e2ekernelengine/crawler/service/NonChannelRssCrawler.java
  src/main/java/com/example/e2ekernelengine/feed/controller/FeedController.java
  src/main/java/com/example/e2ekernelengine/feed/db/repository/FeedRepository.java
  src/main/java/com/example/e2ekernelengine/feed/dto/response/FeedPageableResponse.java
  src/main/java/com/example/e2ekernelengine/feed/dto/response/FeedSearchResponseDto.java
  src/main/java/com/example/e2ekernelengine/feed/service/FeedService.java
  src/main/java/com/example/e2ekernelengine/home/controller/HomeController.java
  src/main/resources/static/index.html
  src/main/resources/static/searchResults.html
  src/main/resources/templates/assets/mainLogo.png
  src/main/resources/templates/assets/searchIcon.png
  src/main/resources/templates/index.html
Labels: enhancement

#46 [Feature] : add redirection to recent feeds
  src/main/resources/templates/index.html
Labels: enhancement

#50 Feat/#44
  src/main/java/com/example/e2ekernelengine/E2eKernelEngineApplication.java
  src/main/java/com/example/e2ekernelengine/ThymeleafConfig.java
  src/main/resources/application.yml
  src/main/resources/static/assets/mainLogo.png
  src/main/resources/static/assets/searchIcon.png
  src/main/resources/templates/addBlogForm.html
  src/main/resources/templates/fragments.html
  src/main/resources/templates/index.html
  src/main/resources/templates/searchResults.html
Labels: enhancement

#51 [Feature] 검색 결과 화면에 그리고 해당 게시글로 리다이렉션 하는 기능 구현
  src/main/java/com/example/e2ekernelengine/DataLoader.java
  src/main/java/com/example/e2ekernelengine/E2eKernelEngineApplication.java
  src/main/java/com/example/e2ekernelengine/ThymeleafConfig.java
  src/main/java/com/example/e2ekernelengine/feed/controller/FeedController.java
  src/main/java/com/example/e2ekernelengine/feed/service/FeedService.java
  src/main/resources/application.yml
  src/main/resources/static/assets/mainLogo.png
  src/main/resources/static/assets/searchIcon.png
  src/main/resources/templates/addBlogForm.html
  src/main/resources/templates/fragments.html
  src/main/resources/templates/index.html
  src/main/resources/templates/searchResults.html
Labels: enhancement

#56 [Feature] 인증 방식(Session 기반 -> jwt 토큰 기반)
  src/main/java/com/example/e2ekernelengine/E2eKernelEngineApplication.java
  src/main/java/com/example/e2ekernelengine/blog/db/entity/Blog.java
  src/main/java/com/example/e2ekernelengine/blog/db/repository/BlogJpaRepository.java
  src/main/java/com/example/e2ekernelengine/blog/util/BlogOwnerType.java
  src/main/java/com/example/e2ekernelengine/config/SpringSecurityConfig.java
  src/main/java/com/example/e2ekernelengine/config/web/WebConfig.java
  src/main/java/com/example/e2ekernelengine/feed/controller/FeedController.java
  src/main/java/com/example/e2ekernelengine/feed/db/repository/FeedRepository.java
  src/main/java/com/example/e2ekernelengine/feed/service/FeedService.java
  src/main/java/com/example/e2ekernelengine/global/annotation/Converter.java
  src/main/java/com/example/e2ekernelengine/user/controller/UserController.java
  src/main/java/com/example/e2ekernelengine/user/db/entity/User.java
  src/main/java/com/example/e2ekernelengine/user/db/repository/UserRepository.java
  src/main/java/com/example/e2ekernelengine/user/dto/request/UserLoginRequestDto.java
  src/main/java/com/example/e2ekernelengine/user/exception/LoginException.java
  src/main/java/com/example/e2ekernelengine/user/exception/RegisterException.java
  src/main/java/com/example/e2ekernelengine/user/security/CustomUserDetail.java
  src/main/java/com/example/e2ekernelengine/user/service/UserService.java
  src/main/java/com/example/e2ekernelengine/user/token/db/entity/RefreshToken.java
  src/main/java/com/example/e2ekernelengine/user/token/db/repository/RefreshTokenRepository.java
  src/main/java/com/example/e2ekernelengine/user/token/exception/TokenException.java
  src/main/java/com/example/e2ekernelengine/user/token/filter/JwtAuthenticationFilter.java
  src/main/java/com/example/e2ekernelengine/user/token/filter/JwtAuthorizationFilter.java
  src/main/java/com/example/e2ekernelengine/user/token/service/TokenService.java
  src/main/java/com/example/e2ekernelengine/user/util/UserPermissionType.java
  src/main/java/com/example/e2ekernelengine/user/util/UserStatusType.java
  src/main/resources/application.yml
  src/main/resources/templates/login.html
Labels: 🌟 Feature

#60 Update issue templates
  .github/ISSUE_TEMPLATE/todo-issue-template.md
Labels: 📑 Docs

#63 [Refactor] Rss 관련 코드 JavaDoc 추가
  src/main/java/com/example/e2ekernelengine/crawler/service/AbstractRssCrawler.java
  src/main/java/com/example/e2ekernelengine/crawler/service/ChannelRssCrawler.java
  src/main/java/com/example/e2ekernelengine/crawler/service/NonChannelRssCrawler.java
  src/main/java/com/example/e2ekernelengine/crawler/service/RssCrawler.java
Labels: 🔨 Refactor

#70 [Fix] Add search API request on searchResult-page
  src/main/resources/templates/searchResults.html
Labels: 🐞🔨 Bugfix

#73 [Feature] Admin 회원가입 및 Admin 화면 연결
  src/main/java/com/example/e2ekernelengine/domain/home/controller/HomeController.java
  src/main/java/com/example/e2ekernelengine/domain/user/controller/UserController.java
  src/main/java/com/example/e2ekernelengine/domain/user/db/entity/User.java
  src/main/java/com/example/e2ekernelengine/domain/user/dto/request/UserRegisterRequestDto.java
  src/main/resources/templates/signup.html
Labels: 🌟 Feature, 🔙 BE, 📲 FE

#74 [Feature] Add Logger about production & develop
  src/main/java/com/example/e2ekernelengine/domain/user/controller/UserController.java
  src/main/resources/logback-spring-local.xml
  src/main/resources/logback-spring-prod.xml
  src/main/resources/logback-spring.xml
  src/main/resources/logback-variables.properties
Labels: 🔙 BE

#79 [Feature] Spring batch를 이용한 게시글 일별 접속 통계 기능 구현
  module-batch/settings.gradle
  module-batch/src/main/java/com/example/modulebatch/BatchJobScheduler.java
  module-batch/src/main/java/com/example/modulebatch/count/db/entity/FeedStatistics.java
  module-batch/src/main/java/com/example/modulebatch/count/job/MakeFeedStatisticsJobConfig.java
  module-batch/src/main/java/com/example/modulebatch/job/AddFeedFromBlogJobConfig.java
  module-batch/src/main/java/com/example/modulebatch/loadData/job/AddFeedFromBlogJobConfig.java
  src/main/java/com/example/e2ekernelengine/domain/feed/controller/FeedController.java
  src/main/java/com/example/e2ekernelengine/domain/feed/db/entity/Feed.java
  src/main/java/com/example/e2ekernelengine/domain/feed/service/FeedService.java
  src/main/resources/logback-spring-local.xml
  src/main/resources/logback-spring-prod.xml
  src/main/resources/logback-spring.xml
  src/main/resources/logback-variables.properties
  src/main/resources/templates/index.html
  src/main/resources/templates/searchResults.html
Labels: 🌟 Feature, 🔙 BE, 💾 DB

#85 [Feature] 일별 가입한 유저 수를 통계 테이블에 집계하는 기능 구현
  module-batch/src/main/java/com/example/modulebatch/BatchJobScheduler.java
  module-batch/src/main/java/com/example/modulebatch/feed/db/entity/FeedStatistics.java
  module-batch/src/main/java/com/example/modulebatch/feed/job/MakeFeedStatisticsJobConfig.java
  module-batch/src/main/java/com/example/modulebatch/user/db/entity/UserStatistics.java
  module-batch/src/main/java/com/example/modulebatch/user/db/repository/UserStatisticsRepository.java
  module-batch/src/main/java/com/example/modulebatch/user/job/AddDailyRegisteredUserJobConfig.java
  module-batch/src/main/java/com/example/modulebatch/user/job/addDailyRegisteredUserTasklet.java
Labels: 🔙 BE, 💾 DB

#89 [Feature] 메인페이지에 조회순, 최신순 필터 적용
  src/main/java/com/example/e2ekernelengine/domain/feed/controller/FeedController.java
  src/main/java/com/example/e2ekernelengine/domain/feed/service/FeedService.java
  src/main/java/com/example/e2ekernelengine/domain/user/controller/UserController.java
  src/main/resources/templates/fragments.html
  src/main/resources/templates/index.html
  src/main/resources/templates/login.html
  src/main/resources/templates/signup.html
Labels: 🖥️ API, 🔙 BE, 📲 FE

#92 [Refactor] 게시글 접속 횟수 통계 집계 방식의 변경
  module-batch/src/main/java/com/example/modulebatch/BatchJobScheduler.java
  module-batch/src/main/java/com/example/modulebatch/ModuleBatchApplication.java
  module-batch/src/main/java/com/example/modulebatch/feed/job/MakeFeedStatisticsJobConfig.java
  module-batch/src/main/java/com/example/modulebatch/user/db/entity/UserRegisterStatistics.java
  module-batch/src/main/java/com/example/modulebatch/user/db/repository/UserRegisterStatisticsRepository.java
  module-batch/src/main/java/com/example/modulebatch/user/db/repository/UserStatisticsRepository.java
  module-batch/src/main/java/com/example/modulebatch/user/job/AddDailyRegisteredUserJobConfig.java
  module-batch/src/main/java/com/example/modulebatch/user/job/AddDailyRegisteredUserTasklet.java
  module-batch/src/main/resources/application.yml
  src/main/resources/application.yml
Labels: 🔙 BE, 🔨 Refactor

#95 [Feature] mysql 기반 검색 조회순, 최신순 필터 적용 + 페이징
  src/main/java/com/example/e2ekernelengine/domain/feed/controller/FeedController.java
  src/main/java/com/example/e2ekernelengine/domain/feed/db/entity/Feed.java
  src/main/java/com/example/e2ekernelengine/domain/feed/db/repository/FeedRepository.java
  src/main/java/com/example/e2ekernelengine/domain/feed/service/FeedService.java
  src/main/resources/templates/index.html
  src/main/resources/templates/searchResults.html
Labels: 🌟 Feature

#103 :docs: Update README.md
  README.md
Labels: 📑 Docs

#104 [Feature] 싱글 노드 엘라스틱 서치 서버에 데이터 저장하기
  build.gradle
  src/main/java/com/example/e2ekernelengine/crawler/dto/FeedDataDto.java
  src/main/java/com/example/e2ekernelengine/crawler/service/AbstractRssCrawler.java
  src/main/java/com/example/e2ekernelengine/crawler/service/ChannelRssCrawler.java
  src/main/java/com/example/e2ekernelengine/crawler/service/NonChannelRssCrawler.java
  src/main/java/com/example/e2ekernelengine/domain/feed/db/entity/Feed.java
  src/main/java/com/example/e2ekernelengine/domain/feed/db/entity/FeedDocument.java
  src/main/java/com/example/e2ekernelengine/domain/feed/service/FeedService.java
  src/main/java/com/example/e2ekernelengine/domain/search/controller/EsSearchController.java
  src/main/java/com/example/e2ekernelengine/domain/search/repository/CustomFeedSearchRepository.java
  src/main/java/com/example/e2ekernelengine/domain/search/repository/FeedSearchRepository.java
  src/main/java/com/example/e2ekernelengine/domain/search/repository/FeedSearchRepositoryImpl.java
  src/main/java/com/example/e2ekernelengine/domain/search/service/EsSearchService.java
  src/main/java/com/example/e2ekernelengine/global/config/ElasticSearchConfig.java
  src/main/java/com/example/e2ekernelengine/global/config/JpaConfig.java
  src/main/resources/application.yml
  src/main/resources/elasticsearch/docker/Dockerfile
  src/main/resources/elasticsearch/docker/docker-compose.yml
  src/main/resources/elasticsearch/feed/feed-mapping.json
  src/main/resources/elasticsearch/feed/feed-setting.json
Labels: 📑 Docs, 🔙 BE, 💾 DB

#107 [Feature] : 엘라스틱 서치로 검색 기능 구현
  src/main/java/com/example/e2ekernelengine/crawler/dto/FeedDataDto.java
  src/main/java/com/example/e2ekernelengine/domain/blog/db/repository/BlogJpaRepository.java
  src/main/java/com/example/e2ekernelengine/domain/feed/db/entity/FeedDocument.java
  src/main/java/com/example/e2ekernelengine/domain/feed/db/repository/FeedRepository.java
  src/main/java/com/example/e2ekernelengine/domain/feed/service/FeedService.java
  src/main/java/com/example/e2ekernelengine/domain/search/controller/EsSearchController.java
  src/main/java/com/example/e2ekernelengine/domain/search/dto/response/EsFeedPageableResponse.java
  src/main/java/com/example/e2ekernelengine/domain/search/repository/EsFeedSearchRepository.java
  src/main/java/com/example/e2ekernelengine/domain/search/repository/FeedSearchRepository.java
  src/main/java/com/example/e2ekernelengine/domain/search/service/EsSearchService.java
  src/main/java/com/example/e2ekernelengine/global/config/JpaConfig.java
Labels: 🌟 Feature, 🔨 Refactor

#109 [Feature] 데일리 Top 10 피드 리스트를 관리자 페이지에 구현
  src/main/java/com/example/e2ekernelengine/domain/admin/controller/AdminController.java
  src/main/java/com/example/e2ekernelengine/domain/admin/dto/MostVisitedFeedDto.java
  src/main/java/com/example/e2ekernelengine/domain/admin/dto/response/DailyTop10FeedListResponse.java
  src/main/java/com/example/e2ekernelengine/domain/admin/service/AdminService.java
  src/main/java/com/example/e2ekernelengine/domain/statistics/db/entity/FeedStatistics.java
  src/main/java/com/example/e2ekernelengine/domain/statistics/db/repository/DailyFeedStatisticsRepository.java
  src/main/resources/templates/manage/adminPage.html
Labels: 🖥️ API, 🌟 Feature, 🔙 BE, 📲 FE

#129 [Feature] 기본 검색 필터를 elastic search 기반 연관성 높은 결과 순으로 설정 + 필터링 정확도순 추가
  src/main/java/com/example/e2ekernelengine/domain/feed/controller/FeedController.java
  src/main/java/com/example/e2ekernelengine/domain/search/controller/EsSearchController.java
  src/main/resources/templates/index.html
  src/main/resources/templates/searchResults.html
Labels: 🌟 Feature, 📲 FE, 🔨 Refactor

#134 [Feature] 나의 블로그 rss 주소 서비스에 등록하는 api & 화면
  src/main/java/com/example/e2ekernelengine/domain/blog/controller/BlogController.java
  src/main/java/com/example/e2ekernelengine/domain/blog/service/BlogService.java
  src/main/java/com/example/e2ekernelengine/domain/feed/db/entity/Feed.java
  src/main/resources/templates/mypage.html
Labels: 🖥️ API, 🌟 Feature, 🔙 BE, 📲 FE

#136 [Hotfix] 프론트 버그 해결
  src/main/resources/templates/index.html
  src/main/resources/templates/login.html
  src/main/resources/templates/searchResults.html
Labels: 📲 FE, 🐞🔨 Bugfix
